### PR TITLE
Fixed the issue with toggle mode icon #32 and background img of causes.html

### PR DESCRIPTION
**Pull request by shreyan-haldankar**
# Description

Fixed the issue with toggle mode icon that was not getting loaded and fixed the background image to get rendered in causes.html

Fixes:  #32 

## Type of change: 

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have made this from my own
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK

### Before fixing The icon issue

image

### After fixing the Dark mode/ Light mode Toggle Icon issue:
image

### Before fixing the background image of causes.html:
image

### After fixing the background image of causes.html:
image

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
Why you changed the whole UI design of causes section ? Also the main photos changed.

**Comment by Sulagna-Dutta-Roy** [comment]
Let me check again.

**Comment by shreyan-haldankar** [comment]
I forgot to mention,
There was an issue with the background image of causes.html.

The causes.html already had the background image
It was just not linked properly, So i fixed it.

Refer line no. 15
Before:
image


After:
image

**Comment by Sulagna-Dutta-Roy** [comment]
Excellent work and reviewed your PR. Thanks for contributing here

**Pull request merged**
