### PR TITLE
Modified appearance of Wash-hands.html, Wear_mask.html and Get_vaccin…

### PR DESCRIPTION
**Pull request by ShuYiKang**
…ated.html; Added back button for the mentioned pages, Added photos on the mentioned webpages

# Description
Hi there, I've enhanced the appearances of three webpages: Wash-hands.html, Wear_mask.html and Get_vaccinated.html. 

- Added <br> in between paragraphs
- Increased font size for h1 and h2
- Added content relevant images next to the paragraphs
- Fixed minor spelling errors
- Added back button 
- Modified line spacing for <p> tag
- Modified padding 
- Linked the "style.css" stylesheet to all three webpages
- Added column and row classes to fit paragraphs and images side by side
- 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes:  #(issue no.)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have made this from my own
- [x] I have taken help from some online resourses 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# ATTACH SCREEN-SHOTS / DEPLOYMENT LINK
Screenshot 2022-08-03 at 5 34 18 PM

### CODE REVIEW

**Comment by Sulagna-Dutta-Roy** [comment]
What's your Issue no ????

**Comment by ShuYiKang** [comment]
Hi, it's issue #53. Sorry, this is my first time contributing, my apologies for the mistake.

**Comment by Sulagna-Dutta-Roy** [comment]
No worries.

**Review by Sulagna-Dutta-Roy — APPROVED** [review]

**Comment by khushimarothi** [comment]
@Sulagna-Dutta-Roy  these changes are not visible on the website. Kindly check.

**Pull request merged**
